ROUTINE EnsAlertErrors [Type=INC]
#define EnsAlertErrNoDefaultNotificationOperation  "<EnsAlert>ErrNoDefaultNotificationOperation"
	; Copyright (c) 2021 by InterSystems Corporation.
	; Cambridge, Massachusetts, U.S.A.  All rights reserved.
	; Confidential property of InterSystems Corporation.
#define EnsAlertErrNoDefaultNotificationRecipients "<EnsAlert>ErrNoDefaultNotificationRecipients"
#define EnsAlertErrNoNotificationManager           "<EnsAlert>ErrNoNotificationManager"