ROUTINE EnsPushNotificationsErrors [Type=INC]
#define EnsPushNotificationsErrGeneral                                 "<EnsPushNotifications>ErrGeneral"
	; Copyright (c) 2021 by InterSystems Corporation.
	; Cambridge, Massachusetts, U.S.A.  All rights reserved.
	; Confidential property of InterSystems Corporation.
#define EnsPushNotificationsErrIncompatibleNotificationType            "<EnsPushNotifications>ErrIncompatibleNotificationType"
#define EnsPushNotificationsErrInvalidDeviceIdAppIdAppTokenAssociation "<EnsPushNotifications>ErrInvalidDeviceIdAppIdAppTokenAssociation"
#define EnsPushNotificationsErrNotificationProtocolNotSupported        "<EnsPushNotifications>ErrNotificationProtocolNotSupported"